name: Site

on:
  pull_request:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  site-pr:
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      contents: read

    uses: athackst/ci/.github/workflows/mkdocs_site.yml@main
    with:
      pages: false
      version: 

    secrets: inherit

  site-main:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
      pages: write
      id-token: write

    uses: athackst/ci/.github/workflows/mkdocs_site.yml@main
    with:
      pages: true
      version: 

    secrets: inherit


  site-release:
    if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
    permissions:
      contents: write
      pages: write
      id-token: write
    uses: athackst/ci/.github/workflows/mkdocs_site.yml@main
    with:
      pages: true
      version: 
      release-tag: ${{ github.event.release.tag_name }}
    secrets: inherit

